### ISSUE TITLE
dry-run fails when the collection does not exists yet

### ISSUE THREAD

**Issue by tarekziade** [pocmo/Fennec-DLC-Catalog#4]
```
$ bin/python create_catalog.py --url http://localhost/v1/buckets/fennec/collections/catalog --auth sebastian:xxx
=== DRY RUN === (Use --force to actually perform those actions)
creating bucket
adding the collection
Traceback (most recent call last):
  File "create_catalog.py", line 203, in <module>
    main()
  File "create_catalog.py", line 192, in main
    existing = fetch_records(session, url=url)
  File "create_catalog.py", line 44, in fetch_records
    response.raise_for_status()
  File "/data/Fennec-DLC-Catalog/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://localhost/v1/buckets/fennec/collections/catalog/records
```

**Comment by leplatrem** [comment]
I don't think it was a dry run

**Comment by tarekziade** [comment]
I confirm it was a dry run.  see "=== DRY RUN ==="  ;)

**Comment by tarekziade** [comment]
Paste from Daniel back then 

``` sh

$ bin/python create_catalog.py --url http://localhost/v1/buckets/fennec/collections/catalog --auth sebastian:xxxx
=== DRY RUN === (Use --force to actually perform those actions)
creating bucket
adding the collection
Traceback (most recent call last):
  File "create_catalog.py", line 203, in <module>
    main()
  File "create_catalog.py", line 192, in main
    existing = fetch_records(session, url=url)
  File "create_catalog.py", line 44, in fetch_records
    response.raise_for_status()
  File "/data/Fennec-DLC-Catalog/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://localhost/v1/buckets/fennec/collections/catalog/records
```
